	;; File generated by GBDK 2.0, P. Felber & M. Hope, 1995-1998


	;; Ordering of segments for the linker
	.area	_CODE
	.area	_DATA
	.area	_LIT
	.area	_BSS

	.globl	_UpdateObjScrPos
	.area	_CODE
_start_UpdateObjScrPos:
_UpdateObjScrPos:
.L2:
	RET
_end_UpdateObjScrPos:
	;; _CODE ends
	;; End of program
