; ROOM1.INC
;
; Map Include File.
;
; Info:
;   Section       : Room1
;   Bank          : 0
;   Map size      : 20 x 18
;   Tile set      : C:\WINDOWS\Desktop\pitfall 2600 tiles.gbr
;   Plane count   : 2 planes (16 bits)
;   Plane order   : Planes are continues
;   Tile offset   : 0
;   Split data    : No
;
; This file was generated by GBMB v1.7

Room1Width  EQU 20
Room1Height EQU 18
Room1Bank   EQU 0

 GLOBAL Room1
 GLOBAL Room1PLN0
 GLOBAL Room1PLN1

; End of ROOM1.INC
