; ATVILOGO.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 20
;
;   Palette colors       : Included.
;   SGB Palette          : None.
;   CGB Palette          : Constant per entry.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2


; Start of tile array.
ATVILogoTileData::
DB $F8,$08,$F8,$68,$D8,$5F,$8F,$1A
DB $FF,$6A,$08,$FF,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$8A,$FF,$DF,$8A
DB $9D,$CA,$89,$FE,$87,$C6,$AF,$E8
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $18,$10,$00,$00,$94,$FF,$DF,$B5
DB $DF,$95,$B4,$FF,$83,$83,$85,$86
DB $2F,$2F,$F0,$DF,$4C,$AD,$5A,$F7
DB $50,$B9,$B0,$D9,$1A,$37,$2D,$2D
DB $55,$77,$42,$65,$57,$ED,$4F,$F5
DB $5F,$F5,$55,$FF,$40,$C0,$40,$C0
DB $F0,$F0,$01,$F1,$4A,$5B,$A6,$F5
DB $AC,$FA,$A4,$FC,$A8,$F8,$50,$50
DB $2A,$3D,$BA,$AF,$38,$2F,$38,$2F
DB $38,$29,$2A,$3B,$00,$00,$00,$00
DB $FE,$FE,$00,$FE,$3A,$BA,$A7,$9D
DB $49,$FB,$B5,$3F,$45,$FF,$BA,$BA
DB $AF,$D8,$AF,$FE,$DB,$A8,$FB,$AA
DB $FF,$AE,$8F,$F8,$00,$00,$00,$00
DB $00,$00,$00,$00,$E9,$E9,$BC,$55
DB $D6,$7B,$57,$FC,$12,$FB,$E9,$E9
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$FF,$00,$00,$FF,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$FF,$00,$00,$FF,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$00,$FF,$00,$00,$FF,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$03,$FE,$06,$0C,$FE,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00

; End of ATVILOGO.Z80
